# Generated by Django 5.2.3 on 2025-06-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('PDM', 'PDM'), ('Analytics', 'Analytics & Development'), ('Order Management', 'Order Management & Price Setup')], max_length=50),
        ),
    ]
